---
version: '3.2'
services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    hostname: adguard
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "8853:8853/udp"
    environment:
      TZ: America/Puerto_Rico
    volumes:
      - './work/:/opt/adguardhome/work/'
      - './conf/:/opt/adguardhome/conf/'
      - './certs:/etc/adguard'
    networks:
      adguard:
        ipv4_address: 172.19.0.2
    restart: always
    cap_add:
      - NET_ADMIN

networks:
 adguard:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1
